controller_list:
  - name: "ur5_arm_right"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: "right_gripper"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_finger1_joint
  - name: "ur5_arm_left"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - 2_shoulder_pan_joint
      - 2_shoulder_lift_joint
      - 2_elbow_joint
      - 2_wrist_1_joint
      - 2_wrist_2_joint
      - 2_wrist_3_joint
  - name: "left_gripper"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - 2_gripper_finger1_joint
